version: '3'
services:
  web:
    image: django_alpine
    environment:
    - NAME=highhopes
    - USER=user
    - PASSWORD=yourpassword
    - HOST=127.0.0.1
    - PORTDB=3307
    network_mode: "host"
    container_name: "project_highhopes_container"
    command: python3 manage.py migrate
    command: python3 manage.py runserver
    volumes:
     - .:/app
